server:
  port: 9097

logging:
  level:
    root: info

#DB
spring:
  jackson:
    deserialization:
      fail-on-ignored-properties: true
      fail-on-unknown-properties: true
  mail:
    host: smtp.mail.ru
    port: 587
    username: bordun.2002@mail.ru
    password: Y6nh9cUhkG0kxNDvH2x6
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  rabbitmq:
    username: user
    password: password
    host: localhost
    port: 5672
    stream:
      username: user
      password: password
      host: localhost
      port: 64823

#for handshake
endpoint: /websocket-server

stomp:
  broker:
    relay: /queue
destination:
  prefix: /app
