version: '3'
services:
  master_postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
  master_redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"

  master_rabbit:
    image: aiwin/rabbitmq-stomp:latest
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - '5672:5672' #Default port of RabbitMQ
      - '15672:15672' #RabbitMQ Web UI
      - '61613:61613' #STOMP port

  aviasales:
    container_name: aviasales
    build:
      context: ./aviasales
    ports:
      - "9095:9095"
    depends_on:
      - master_redis
      - master_postgres
      - master_rabbit
