#DB
server:
  tomcat:
    relaxed-query-chars: '[,]'
  port: 9096

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none

  liquibase:
    change-log:
      'classpath:db/changelog/db.changelog-master.yaml'

  rabbitmq:
    username: user
    password: password
    host: localhost
    port: 5672

springdoc:
  swagger-ui:
    path: /swagger-ui.html
